# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flipt/flipt.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'flipt/flipt.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x66lipt/flipt.proto\x12\x05\x66lipt\x1a\x1fgoogle/protobuf/timestamp.proto\"w\n\x0fListFlagRequest\x12\r\n\x05limit\x18\x01 \x01(\x05\x12\x12\n\npage_token\x18\x02 \x01(\t\x12\x15\n\rnamespace_key\x18\x03 \x01(\t\x12\x11\n\treference\x18\x04 \x01(\t\x12\x17\n\x0f\x65nvironment_key\x18\x05 \x01(\t\"\xe2\x01\n\x07Variant\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08\x66lag_key\x18\x02 \x01(\t\x12\x0b\n\x03key\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12.\n\ncreated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\nattachment\x18\x08 \x01(\t\x12\x15\n\rnamespace_key\x18\t \x01(\t\"\xff\x01\n\x04\x46lag\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0f\n\x07\x65nabled\x18\x04 \x01(\x08\x12.\n\ncreated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12 \n\x08variants\x18\x07 \x03(\x0b\x32\x0e.flipt.Variant\x12\x15\n\rnamespace_key\x18\x08 \x01(\t\x12\x1d\n\x04type\x18\t \x01(\x0e\x32\x0f.flipt.FlagType\"T\n\x08\x46lagList\x12\x1a\n\x05\x66lags\x18\x01 \x03(\x0b\x32\x0b.flipt.Flag\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0btotal_count\x18\x03 \x01(\x05*8\n\x08\x46lagType\x12\x15\n\x11VARIANT_FLAG_TYPE\x10\x00\x12\x15\n\x11\x42OOLEAN_FLAG_TYPE\x10\x01\x32=\n\x05\x46lipt\x12\x34\n\tListFlags\x12\x16.flipt.ListFlagRequest\x1a\x0f.flipt.FlagListB\x1dZ\x1bgo.flipt.io/flipt/rpc/fliptb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flipt.flipt_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\033go.flipt.io/flipt/rpc/flipt'
  _globals['_FLAGTYPE']._serialized_start=755
  _globals['_FLAGTYPE']._serialized_end=811
  _globals['_LISTFLAGREQUEST']._serialized_start=61
  _globals['_LISTFLAGREQUEST']._serialized_end=180
  _globals['_VARIANT']._serialized_start=183
  _globals['_VARIANT']._serialized_end=409
  _globals['_FLAG']._serialized_start=412
  _globals['_FLAG']._serialized_end=667
  _globals['_FLAGLIST']._serialized_start=669
  _globals['_FLAGLIST']._serialized_end=753
  _globals['_FLIPT']._serialized_start=813
  _globals['_FLIPT']._serialized_end=874
# @@protoc_insertion_point(module_scope)
